name: OvaFlus
options:
  bundleIdPrefix: com.ovaflus
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "15.0"

settings:
  base:
    SWIFT_VERSION: "5.9"
    DEVELOPMENT_TEAM: ""

packages:
  amplify-swift:
    url: https://github.com/aws-amplify/amplify-swift.git
    from: "2.0.0"

targets:
  OvaFlus:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: OvaFlus
        excludes:
          - "OvaFlusWidget/**"
    resources:
      - path: OvaFlus/Info.plist
        optional: true
    dependencies:
      - package: amplify-swift
        product: Amplify
      - package: amplify-swift
        product: AWSCognitoAuthPlugin
      - package: amplify-swift
        product: AWSAPIPlugin
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.ovaflus.app
        INFOPLIST_FILE: OvaFlus/Info.plist
        CODE_SIGN_STYLE: Automatic

  OvaFlusWidget:
    type: app-extension
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: OvaFlus/OvaFlusWidget
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.ovaflus.app.widget
        INFOPLIST_FILE: OvaFlus/OvaFlusWidget/Info.plist
